version: 2

jobs:
  jshint:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Installing jshint
          command: sudo npm install -g jshint
      - run:
          name: Running jshint
          command: jshint resources/timeseries.js resources/stuquery.js resources/graph.js
  tests:
    docker:
      - image: circleci/python:3.7.1-browsers
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: sudo pip install pytest flask flask-cors selenium
      - run:
          name: Running tests
          command: pytest tests/test_examples.py


workflows:
  version: 2
  tests_and_docs:
    jobs:
      - jshint
      - tests
